const ar = {
  assistant: "مساعد Restrova",
  conversation: "المحادثة",
  you: "أنت",
  title: "من بياناتك إلى قرار واضح",
  subtitle: "اسأل عن أداء فرعك، وخذ خلاصة وخطوة عملية.",
  welcome: "حيّاك. أقدر أحلل بياناتك المستوردة وأوضح لك أداء المبيعات وربحية الأصناف. وش تحب نراجع؟",
  brief: "نظرة على الفترة الحالية",
  month: "هذا الشهر",
  today: "اليوم",
  sales: "صافي المبيعات",
  profit: "الربح التقديري",
  orders: "طلبات",
  margin: "هامش الربح",
  stock: "تنبيهات المخزون",
  dish: "الصنف الأعلى مبيعًا",
  stockAction: "عناصر تحتاج مراجعة",
  noInventory: "لم تُربط بيانات المخزون",
  noSales: "لا توجد سجلات للفترة الحالية",
  unavailable: "غير متاح",
  loading: "جارٍ تحميل البيانات",
  connected: "بيانات مستوردة",
  recorded: "سجلات المطعم",
  noData: "بانتظار البيانات",
  dataError: "تعذّر تحميل بعض البيانات. حاول التحديث مرة ثانية.",
  retry: "تحديث البيانات",
  import: "استيراد وإدارة البيانات",
  fresh: "محادثة جديدة",
  send: "إرسال الرسالة",
  thinking: "جارٍ مراجعة بيانات الفرع…",
  placeholder: "اسأل عن مبيعاتك، ربحية الأصناف، أو البيانات اللي استوردتها…",
  disclaimer: "الأرقام من سجلات فرعك. التوصيات تحتاج مراجعتك قبل التنفيذ.",
  sendError: "تعذّر إرسال الرسالة. حاول مرة ثانية.",
  malformed: "وصل رد غير مكتمل. حاول مرة ثانية.",
  prompts: ["حلل البيانات اللي استوردتها", "وش أكثر الأصناف مبيعًا؟", "وش يحتاج انتباهي؟"],
  feedback: "هل كانت الإجابة مفيدة ودقيقة؟",
  approve: "مفيدة",
  correct: "تصحيح",
  correction: "الإجابة الصحيحة",
  saveCorrection: "حفظ التصحيح",
  feedbackError: "ما قدرنا نحفظ ملاحظتك. حاول مرة ثانية.",
  dismiss: "إغلاق التقييم",
  evidence: "مرجع الإجابة",
  costsMissing: "التكاليف غير مكتملة"
};
const en = {
  assistant: "Restrova assistant",
  conversation: "Conversation",
  you: "You",
  title: "Turn your data into a clear decision",
  subtitle: "Ask about your branch. Get the evidence and a practical next step.",
  welcome: "Welcome. I can analyze imported sales and item profitability. What would you like to review?",
  brief: "Current period at a glance",
  month: "This month",
  today: "Today",
  sales: "Net sales",
  profit: "Estimated profit",
  orders: "orders",
  margin: "margin",
  stock: "Stock alerts",
  dish: "Top dish",
  stockAction: "items to review",
  noInventory: "Inventory not connected",
  noSales: "No sales records for this period",
  unavailable: "Unavailable",
  loading: "Loading data",
  connected: "Imported data",
  recorded: "Restaurant records",
  noData: "Awaiting data",
  dataError: "Some data could not be loaded. Please refresh and try again.",
  retry: "Refresh data",
  import: "Import & manage data",
  fresh: "New conversation",
  send: "Send message",
  thinking: "Reviewing your branch data…",
  placeholder: "Ask for a decision about sales, item profit, or imported data…",
  disclaimer: "Figures come from your branch records. Review recommendations before taking action.",
  sendError: "The message could not be sent. Please try again.",
  malformed: "The response was incomplete. Please try again.",
  prompts: ["Analyze my imported data", "Which dishes sell best?", "What needs my attention?"],
  feedback: "Was this answer useful and accurate?",
  approve: "Approve",
  correct: "Correct",
  correction: "Correct answer",
  saveCorrection: "Save correction",
  feedbackError: "Your feedback could not be saved. Please try again.",
  dismiss: "Dismiss feedback",
  evidence: "Answer source",
  costsMissing: "Costs incomplete"
};
const zh = {
  assistant: "Restrova 助手",
  conversation: "对话",
  you: "你",
  title: "从数据到清晰的决策",
  subtitle: "了解分店表现，获取有依据的分析和下一步建议。",
  welcome: "欢迎。我可以分析导入的销售数据和菜品盈利情况。你想先了解什么？",
  brief: "当前期间概览",
  month: "本月",
  today: "今天",
  sales: "净销售额",
  profit: "预计利润",
  orders: "订单",
  margin: "利润率",
  stock: "库存提醒",
  dish: "最畅销菜品",
  stockAction: "项需要检查",
  noInventory: "尚未连接库存",
  noSales: "此期间没有销售记录",
  unavailable: "暂无数据",
  loading: "正在加载数据",
  connected: "已导入数据",
  recorded: "餐厅记录",
  noData: "等待数据",
  dataError: "部分数据加载失败，请刷新重试。",
  retry: "刷新数据",
  import: "导入和管理数据",
  fresh: "新对话",
  send: "发送消息",
  thinking: "正在查看分店数据…",
  placeholder: "询问销售、菜品利润或已导入的数据…",
  disclaimer: "数据来自当前分店。请在执行建议前进行审核。",
  sendError: "消息发送失败，请重试。",
  malformed: "回复不完整，请重试。",
  prompts: ["Analyze my imported data", "Which dishes sell best?", "What needs my attention?"],
  feedback: "回复是否准确且有帮助？",
  approve: "有帮助",
  correct: "纠正",
  correction: "正确回复",
  saveCorrection: "保存纠正",
  feedbackError: "反馈保存失败，请重试。",
  dismiss: "关闭反馈",
  evidence: "回复来源",
  costsMissing: "成本不完整"
};
export const workspaceCopy = { ar, en, "zh-CN": zh };
