import { useState } from 'react';

const api = (import.meta.env.VITE_API_URL as string | undefined) ?? 'http://127.0.0.1:3000';
const text = { en: { title: 'Restaurant setup', profile: 'Restaurant profile', branch: 'Add branch', channel: 'Add sales channel', save: 'Save', complete: 'Onboarding checklist', name: 'Name', legal: 'Legal name', country: 'Country', city: 'City', timezone: 'Timezone', currency: 'Currency', language: 'Language', success: 'Saved successfully' }, ar: { title: 'إعداد المطعم', profile: 'ملف المطعم', branch: 'إضافة فرع', channel: 'إضافة قناة مبيعات', save: 'حفظ', complete: 'قائمة الإعداد', name: 'الاسم', legal: 'الاسم القانوني', country: 'الدولة', city: 'المدينة', timezone: 'المنطقة الزمنية', currency: 'العملة', language: 'اللغة', success: 'تم الحفظ بنجاح' } } as const;

export function App() {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [authenticated, setAuthenticated] = useState(false); const [locale, setLocale] = useState<'en' | 'ar'>('en'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const t = text[locale];
  async function auth(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const r = await fetch(`${api}/auth/${mode}`, { method: 'POST', credentials: 'include', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); if (!r.ok) throw new Error(); setAuthenticated(true); } catch { setMessage('Unable to authenticate'); } finally { setBusy(false); } }
  async function saveProfile(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); try { const r = await fetch(`${api}/onboarding/profile`, { method: 'PUT', credentials: 'include', headers: { 'content-type': 'application/json', 'x-csrf-token': document.cookie.match(/rda_csrf=([^;]+)/)?.[1] ?? '' }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget).entries())) }); if (!r.ok) throw new Error(); setMessage(t.success); } catch { setMessage('Unable to save'); } finally { setBusy(false); } }
  if (authenticated) return <main dir={locale === 'ar' ? 'rtl' : 'ltr'} className="dashboard"><header><div><p className="eyebrow">RESTAURANT DECISION AI</p><h1>{t.title}</h1></div><button onClick={() => setLocale(locale === 'en' ? 'ar' : 'en')}>{locale === 'en' ? 'العربية' : 'English'}</button></header><section className="import-card"><h2>{t.profile}</h2><form onSubmit={saveProfile}><label>{t.name}<input name="name" required /></label><label>{t.legal}<input name="legalName" /></label><label>{t.country}<input name="country" /></label><label>{t.city}<input name="city" /></label><label>{t.currency}<input name="currency" defaultValue="CNY" maxLength={3} required /></label><label>{t.timezone}<input name="timezone" defaultValue="Asia/Shanghai" required /></label><label>{t.language}<select name="defaultLanguage" value={locale} onChange={(e) => setLocale(e.target.value as 'en' | 'ar')}><option value="en">English</option><option value="ar">العربية</option></select></label><button disabled={busy}>{t.save}</button></form>{message && <p role="status">{message}</p>}</section><section className="decision-card"><h2>{t.complete}</h2><p>✓ Organization and owner account</p><p>✓ Restaurant profile</p><p>○ Branches</p><p>○ Sales channels</p><p>○ Team invitations</p><p>○ First CSV/XLSX import</p></section></main>;
  return <main className="auth-shell"><section><p className="eyebrow">RESTAURANT DECISION AI</p><h1>{mode === 'login' ? 'Welcome back' : 'Create your workspace'}</h1><form onSubmit={auth}><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" minLength={12} required /></label>{mode === 'register' && <><label>Name<input name="displayName" required /></label><label>Organization<input name="organizationName" required /></label><label>Restaurant<input name="restaurantName" required /></label></>}<button disabled={busy}>{mode === 'login' ? 'Sign in' : 'Register'}</button>{message && <p role="alert">{message}</p>}</form><button className="link-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Create an account' : 'I already have an account'}</button></section></main>;
}
