export const copilotUiCopy = {
  ar: {
    noLoss: "ما ظهرت خسارة في الفروع المكتملة.",
    excluded: "فروع مستبعدة لنقص البيانات",
    forecastNote: "تقدير تاريخي غير مضمون",
    title: "مساعد رستروفا",
    intro: "اسأل عن بياناتك المستوردة، وشوف الأدلة وراء كل نتيجة.",
    report: "التقرير اليومي",
    reportIntro: "ملخص السجلات المكتملة، وأهم التغيّرات اللي تحتاج متابعة.",
    scope: "نطاق التحليل",
    restaurant: "المطعم",
    branch: "الفرع المحدد",
    from: "من",
    to: "إلى",
    send: "إرسال",
    placeholder: "مثال: ليش انخفض الربح هذا الأسبوع؟",
    new: "محادثة جديدة",
    history: "محادثاتي",
    loading: "جاري قراءة البيانات…",
    error: "تعذّر إكمال الطلب. حدّث البيانات أو اختر فترة أقصر وحاول مرة ثانية.",
    retry: "تحديث",
    sources: "عرض الأدلة",
    stale: "هذه إجابة محفوظة قبل آخر تحديث للبيانات؛ أعد السؤال لتحديثها.",
    imports: "استيراد البيانات",
    revision: "إصدار البيانات",
    noData: "غير متاح: البيانات غير كافية",
    period: "الفترة",
    source: "فتح صفحة المصدر",
    private: "محادثاتك خاصة بحسابك وتخضع لصلاحياتك الحالية.",
    suggestions: [
      "ليش انخفض الربح هذا الأسبوع؟",
      "إيش تغير أمس؟",
      "أي فرع خسر أكثر؟",
      "ليش زادت تكلفة الطعام؟",
      "أي أصناف أراجع سعرها؟",
      "اعرض توقع الإيراد",
      "اعرض التنبيهات"
    ],
    empty: "ابدأ بسؤال أو اختر مثالًا.",
    saved: "إجابة محفوظة",
    note: "هذا تحليل للسجلات، وليس إثباتًا لسبب تشغيلي أو ضمانًا للنتيجة.",
    confidence: "حالة الدليل",
    supported: "مدعوم بالبيانات",
    insufficient: "بيانات ناقصة"
  },
  en: {
    noLoss: "No loss recorded among complete branches.",
    excluded: "Branches excluded for missing data",
    forecastNote: "Historical estimate, not a guarantee",
    title: "Restrova copilot",
    intro: "Ask about imported data and inspect the evidence behind each conclusion.",
    report: "Daily report",
    reportIntro: "A summary of completed records and changes that need attention.",
    scope: "Analysis scope",
    restaurant: "Restaurant",
    branch: "Selected branch",
    from: "From",
    to: "To",
    send: "Send",
    placeholder: "Why did profit decrease this week?",
    new: "New conversation",
    history: "My conversations",
    loading: "Reading data…",
    error: "Unable to complete request. Refresh or select a shorter period and retry.",
    retry: "Refresh",
    sources: "Inspect evidence",
    stale: "This answer predates the latest data revision. Ask again to refresh it.",
    imports: "Import data",
    revision: "Data revision",
    noData: "Unavailable: insufficient evidence",
    period: "Period",
    source: "Open source page",
    private: "Conversations are private to your account and follow your current permissions.",
    suggestions: [
      "Why did profit decrease this week?",
      "What changed yesterday?",
      "Which branch lost most money?",
      "Why did food cost increase?",
      "Which dishes should I reprice?",
      "Show revenue forecasts",
      "Show alerts"
    ],
    empty: "Ask a question or choose an example.",
    saved: "Saved answer",
    note: "This describes recorded evidence, not an operational causal claim or a guaranteed outcome.",
    confidence: "Evidence status",
    supported: "Supported",
    insufficient: "Insufficient evidence"
  },
  zh: {
    noLoss: "完整数据门店未记录亏损。",
    excluded: "因数据缺失排除的门店",
    forecastNote: "基于历史的估计，并非保证",
    title: "Restrova 智能助手",
    intro: "询问导入数据，并查看每项结论的证据。",
    report: "每日经营报告",
    reportIntro: "完整记录摘要及需要关注的变化。",
    scope: "分析范围",
    restaurant: "餐厅",
    branch: "所选门店",
    from: "开始",
    to: "结束",
    send: "发送",
    placeholder: "为什么本周利润下降？",
    new: "新对话",
    history: "我的对话",
    loading: "正在读取数据…",
    error: "请求失败，请刷新或缩短期间后重试。",
    retry: "刷新",
    sources: "查看证据",
    stale: "数据在此回答后已更新，请重新提问。",
    imports: "导入数据",
    revision: "数据版本",
    noData: "不可用：证据不足",
    period: "期间",
    source: "打开来源页面",
    private: "对话仅限本人，并受当前权限限制。",
    suggestions: [
      "为什么本周利润下降？",
      "昨天有什么变化？",
      "哪家门店亏损最多？",
      "食材成本为什么上涨？",
      "哪些菜品需要调价？",
      "显示收入预测",
      "显示提醒"
    ],
    empty: "输入问题或选择示例。",
    saved: "已保存的回答",
    note: "分析描述记录证据，不证明运营因果关系或保证结果。",
    confidence: "证据状态",
    supported: "有证据支持",
    insufficient: "证据不足"
  }
};
