export const decisionCopy = {
  ar: {
    foodCost: "تكلفة المكونات المقترحة (هللات)",
    packagingCost: "تكلفة التغليف المقترحة (هللات)",
    title: "مركز التوصيات",
    intro: "توصيات من بياناتك المستوردة، بأدلتها وخطوات متابعة واضحة.",
    imports: "استيراد البيانات",
    forecast: "التوقعات",
    revision: "إصدار البيانات",
    empty: "ما عندنا أدلة كافية لتوصية الآن. استورد المبيعات وتكاليف الأصناف، وتأكد من الفرع والفترة.",
    loading: "جاري قراءة البيانات…",
    error: "تعذّر إكمال الطلب. تحقق من البيانات وحاول مرة ثانية.",
    branch: "اختر فرعًا من القائمة العلوية",
    from: "من",
    to: "إلى",
    evidence: "الأدلة المسجلة",
    impact: "الأثر المسجل",
    unknown: "غير متاح",
    expected: "الأثر المتوقع يحتاج سيناريو؛ ما نقدر نضمن النتيجة.",
    record: "حفظ للمتابعة",
    tracking: "متابعة القرارات",
    proposed: "مقترحة",
    accepted: "معتمدة",
    rejected: "مرفوضة",
    action_taken: "تم التنفيذ",
    measured: "تم القياس",
    accept: "اعتماد",
    reject: "رفض",
    act: "تسجيل التنفيذ",
    measure: "قياس النتيجة",
    note: "ملاحظة القرار أو تفاصيل التنفيذ",
    days: "مدة القياس بالأيام",
    scenario: "سيناريو السعر أو العرض",
    price: "السعر المقترح (هللات)",
    demand: "تغيّر الطلب المفترض (نقاط أساس، مفصولة بفاصلة)",
    floor: "الحد الأدنى لهامش المساهمة (نقاط أساس)",
    run: "حساب السيناريو",
    eligible: "السيناريو يحقق حد الهامش؛ راجع الافتراضات قبل التنفيذ.",
    blocked: "السيناريو غير مؤهل أو البيانات ناقصة.",
    observational: "الفرق قبل وبعد من المبيعات المستوردة؛ ما يثبت أن القرار وحده سبب التغيير.",
    cost: "التكاليف",
    pricing: "التسعير",
    menu: "القائمة",
    branchType: "الفروع",
    promotion: "العروض",
    saveForecast: "حفظ توقع اليوم للقياس لاحقًا",
    saved: "تم الحفظ",
    accuracy: "دقة التوقعات المسجلة",
    mae: "متوسط الخطأ المطلق",
    mape: "متوسط الخطأ النسبي",
    count: "مشاهدات",
    interval: "نطاق الإيراد التقديري 80%",
    uncertainty: "النطاق مستخرج من أخطاء تاريخية، وتغطيته غير مضمونة. لا يشمل مجموع الفروع أو الأرباح.",
    seasons: "المواسم والأحداث",
    seasonIntro:
      "سجّل تواريخ رمضان والعيد والإجازات والأحداث المحلية ومواسم مطعمك مع مصدرها. المقارنة تستخدم نفس يوم الأسبوع ونوع الموسم؛ نقص التاريخ يوقف التوقع.",
    name: "اسم الحدث",
    source: "مصدر التواريخ",
    add: "إضافة الحدث",
    ramadan: "رمضان",
    eid: "العيد",
    weekend: "عطلة الأسبوع",
    holiday: "إجازة",
    local_event: "حدث محلي",
    restaurant: "موسم المطعم",
    stable: "مستقر",
    increased_error: "ارتفع الخطأ",
    insufficient_data: "بيانات غير كافية",
    noGuarantee: "تقدير مشروط، وليس نتيجة مضمونة",
    refresh: "تحديث",
    connected: "تم ربط البيانات بالتحليلات والتوصيات ومساحة العمل.",
    alerts: "التنبيهات"
  },
  en: {
    foodCost: "Proposed food cost (minor units)",
    packagingCost: "Proposed packaging cost (minor units)",
    title: "Decision center",
    intro: "Recommendations from confirmed imports, with evidence and measurable follow-up.",
    imports: "Import data",
    forecast: "Forecasts",
    revision: "Data revision",
    empty: "No supported recommendation yet. Import item sales and costs, then check branch and dates.",
    loading: "Reading data…",
    error: "Unable to complete request. Check the data and retry.",
    branch: "Select a branch in the top bar",
    from: "From",
    to: "To",
    evidence: "Recorded evidence",
    impact: "Observed impact",
    unknown: "Unavailable",
    expected: "Expected impact requires a scenario; outcomes are not guaranteed.",
    record: "Save for follow-up",
    tracking: "Decision follow-up",
    proposed: "Proposed",
    accepted: "Accepted",
    rejected: "Rejected",
    action_taken: "Action taken",
    measured: "Measured",
    accept: "Accept",
    reject: "Reject",
    act: "Record action",
    measure: "Measure result",
    note: "Decision note or action details",
    days: "Observation days",
    scenario: "Price or promotion scenario",
    price: "Proposed price (minor units)",
    demand: "Assumed demand changes (basis points, comma separated)",
    floor: "Minimum contribution margin (basis points)",
    run: "Calculate scenario",
    eligible: "Meets the margin floor; review assumptions before acting.",
    blocked: "Not eligible or insufficient evidence.",
    observational: "Imported sales before and after; the change does not prove the action caused it.",
    cost: "Costs",
    pricing: "Pricing",
    menu: "Menu",
    branchType: "Branches",
    promotion: "Promotions",
    saveForecast: "Save today's forecast for later scoring",
    saved: "Saved",
    accuracy: "Recorded forecast accuracy",
    mae: "Mean absolute error",
    mape: "Mean absolute percentage error",
    count: "Observations",
    interval: "Estimated 80% revenue band",
    uncertainty: "Historical error band; coverage is not guaranteed. Group and profit intervals are unavailable.",
    seasons: "Seasons and events",
    seasonIntro:
      "Record Ramadan, Eid, holidays, local events and restaurant seasons with a date source. Comparisons match weekday and season kind; sparse history withholds forecasts.",
    name: "Event name",
    source: "Date source",
    add: "Add event",
    ramadan: "Ramadan",
    eid: "Eid",
    weekend: "Weekend",
    holiday: "Holiday",
    local_event: "Local event",
    restaurant: "Restaurant season",
    stable: "Stable",
    increased_error: "Error increased",
    insufficient_data: "Insufficient data",
    noGuarantee: "Conditional estimate, not a guarantee",
    refresh: "Refresh",
    connected: "Data connected to analytics, recommendations and workspace.",
    alerts: "Alerts"
  },
  zh: {
    foodCost: "建议食材成本（最小货币单位）",
    packagingCost: "建议包装成本（最小货币单位）",
    title: "决策中心",
    intro: "根据已确认的导入数据生成建议，并提供证据与效果跟踪。",
    imports: "导入数据",
    forecast: "预测",
    revision: "数据版本",
    empty: "暂无充分证据。请导入商品销售及成本，并检查门店和日期。",
    loading: "读取数据中…",
    error: "操作失败，请检查数据后重试。",
    branch: "请在顶部选择门店",
    from: "开始",
    to: "结束",
    evidence: "记录证据",
    impact: "已观察影响",
    unknown: "不可用",
    expected: "预期效果需要情景分析，结果并无保证。",
    record: "保存并跟踪",
    tracking: "决策跟踪",
    proposed: "已建议",
    accepted: "已批准",
    rejected: "已拒绝",
    action_taken: "已执行",
    measured: "已衡量",
    accept: "批准",
    reject: "拒绝",
    act: "记录执行",
    measure: "衡量结果",
    note: "决策说明或执行详情",
    days: "观察天数",
    scenario: "价格或促销情景",
    price: "建议价格（最小货币单位）",
    demand: "假设需求变化（基点，逗号分隔）",
    floor: "最低贡献利润率（基点）",
    run: "计算情景",
    eligible: "符合利润率底线，请先审核假设。",
    blocked: "不符合要求或证据不足。",
    observational: "比较导入的前后销售，变化不证明因果关系。",
    cost: "成本",
    pricing: "定价",
    menu: "菜单",
    branchType: "门店",
    promotion: "促销",
    saveForecast: "保存今日预测以供后续评估",
    saved: "已保存",
    accuracy: "已记录预测准确度",
    mae: "平均绝对误差",
    mape: "平均绝对百分比误差",
    count: "观察数",
    interval: "估算80%收入区间",
    uncertainty: "区间来自历史误差，并不保证覆盖率。不提供门店汇总或利润区间。",
    seasons: "季节和活动",
    seasonIntro:
      "记录斋月、开斋节、假期、本地活动及餐厅季节并注明日期来源。仅比较相同星期与季节，历史不足时不生成预测。",
    name: "活动名称",
    source: "日期来源",
    add: "添加活动",
    ramadan: "斋月",
    eid: "开斋节",
    weekend: "周末",
    holiday: "假期",
    local_event: "本地活动",
    restaurant: "餐厅季节",
    stable: "稳定",
    increased_error: "误差上升",
    insufficient_data: "数据不足",
    noGuarantee: "有条件估算，并非保证",
    refresh: "刷新",
    connected: "数据已连接到分析、建议及工作区。",
    alerts: "提醒"
  }
};
export const actionCopy = {
  ar: {
    foodCost: "تكلفة المكونات المقترحة (هللات)",
    packagingCost: "تكلفة التغليف المقترحة (هللات)",
    promote_item: "ابرز الصنف في القائمة",
    raise_price: "راجع تسعير الصنف",
    reduce_ingredient_cost: "راجع تكلفة المكونات والموردين",
    change_portion: "اختبر تعديل الوصفة أو الحصة",
    bundle_item: "اختبر باقة للصنف",
    consider_removal: "راجع جدوى بقاء الصنف",
    test_targeted_offer: "اختبر عرضًا موجّهًا لهذا الصنف",
    review_supplier_quote: "قارن عروض المورد وتكلفة الوصفة",
    review_falling_sales: "راجع أوقات البيع وتشغيل الفرع",
    review_high_refunds: "راجع أسباب الاسترداد ومصادره",
    review_abnormal_discounts: "راجع صلاحيات الخصم والعروض",
    review_rising_costs: "راجع تغيّر تكاليف الفرع",
    review_underperformance: "قارن تشغيل الفرع بالفروع المؤهلة"
  },
  en: {
    foodCost: "Proposed food cost (minor units)",
    packagingCost: "Proposed packaging cost (minor units)",
    promote_item: "Feature the item",
    raise_price: "Review item pricing",
    reduce_ingredient_cost: "Review ingredients and suppliers",
    change_portion: "Test recipe or portion changes",
    bundle_item: "Test an item bundle",
    consider_removal: "Review whether to retain the item",
    test_targeted_offer: "Test an offer for this item",
    review_supplier_quote: "Compare supplier quotes and recipe costs",
    review_falling_sales: "Review branch selling hours and operations",
    review_high_refunds: "Review refund reasons and sources",
    review_abnormal_discounts: "Review discount permissions and campaigns",
    review_rising_costs: "Review branch cost changes",
    review_underperformance: "Compare operations with eligible peer branches"
  },
  zh: {
    foodCost: "建议食材成本（最小货币单位）",
    packagingCost: "建议包装成本（最小货币单位）",
    promote_item: "突出展示商品",
    raise_price: "审核商品定价",
    reduce_ingredient_cost: "审核原料及供应商",
    change_portion: "测试配方或分量调整",
    bundle_item: "测试商品套餐",
    consider_removal: "审核是否保留商品",
    test_targeted_offer: "测试该商品定向优惠",
    review_supplier_quote: "比较供应商报价与配方成本",
    review_falling_sales: "审核营业时段和门店运营",
    review_high_refunds: "审核退款原因和来源",
    review_abnormal_discounts: "审核折扣权限和活动",
    review_rising_costs: "审核门店成本变化",
    review_underperformance: "与可比门店对照运营情况"
  }
};
