import { useLocale } from "../contexts/LocaleContext.jsx";

export const importTranslations = {
  ar: {
    "Safe staged import": "استيراد آمن على مراحل",
    "Import restaurant data": "استيراد بيانات المطعم",
    "Validate, map and preview CSV/XLSX data before anything is written to your restaurant.":
      "تحقق من بيانات CSV/XLSX وطابق أعمدتها وعاينها قبل حفظها في مطعمك.",
    "Import progress": "مراحل الاستيراد",
    Upload: "رفع الملف",
    Detection: "التعرّف",
    Mapping: "مطابقة الأعمدة",
    Validation: "التحقق",
    Preview: "معاينة",
    Confirm: "تأكيد",
    Selected: "محدد",
    Choose: "اختيار",
    Template: "نموذج",
    required: "مطلوب",
    optional: "اختياري",
    "Smart import": "استيراد ذكي",
    "Automatic detection": "التعرّف التلقائي",
    "CSV or XLSX file": "ملف CSV أو XLSX",
    File: "ملف",
    "High confidence": "ثقة عالية",
    "Review suggested": "يُنصح بالمراجعة",
    Confirmed: "مؤكد",
    "Step 2 · File detected": "الخطوة 2 · تم التعرّف على الملف",
    "Restrova classified this as": "صنّف Restrova هذا الملف على أنه",
    " data and evaluated the uploaded rows.": " وقيّم الصفوف المرفوعة.",
    "Step 3": "الخطوة 3",
    "Review column mapping": "مراجعة مطابقة الأعمدة",
    "Map each uploaded column to a Restrova field. Required fields must be mapped before validation can continue.":
      "طابق كل عمود مرفوع مع حقل في Restrova. يجب مطابقة الحقول المطلوبة قبل متابعة التحقق.",
    "Mapping complete": "اكتملت المطابقة",
    "required missing": "حقول مطلوبة غير مطابقة",
    "Uploaded column": "العمود المرفوع",
    "Restrova field": "حقل Restrova",
    Status: "الحالة",
    Map: "مطابقة",
    "Ignore column": "تجاهل العمود",
    Mapped: "تمت المطابقة",
    Unmapped: "غير مطابق",
    "Save mapping & validate": "حفظ المطابقة والتحقق",
    "Warnings do not necessarily block confirmation.": "التحذيرات لا تمنع التأكيد بالضرورة.",
    "Fix these rows and upload again before confirming.": "صحح هذه الصفوف وارفع الملف مجددًا قبل التأكيد.",
    Row: "الصف",
    Column: "العمود",
    Value: "القيمة",
    Message: "الرسالة",
    "Step 4": "الخطوة 4",
    "Validation results": "نتائج التحقق",
    "Review accepted, rejected, duplicate and warning counts before confirming the import.":
      "راجع عدد الصفوف المقبولة والمرفوضة والمكررة والتحذيرات قبل تأكيد الاستيراد.",
    "Ready to confirm": "جاهز للتأكيد",
    "Action required": "يلزم إجراء",
    "Total rows": "إجمالي الصفوف",
    Valid: "صحيح",
    Invalid: "غير صحيح",
    Duplicates: "المكررات",
    Warnings: "التحذيرات",
    "Blocking errors": "أخطاء تمنع الاستيراد",
    "Unmapped optional columns": "أعمدة اختيارية غير مطابقة",
    "These columns will be ignored unless you map them manually.": "سيتم تجاهل هذه الأعمدة ما لم تطابقها يدويًا.",
    "Step 5": "الخطوة 5",
    "Showing up to 20 rows using the original uploaded column names.":
      "عرض ما يصل إلى 20 صفًا بأسماء الأعمدة الأصلية في الملف.",
    "Safe to import": "آمن للاستيراد",
    Blocked: "محظور",
    "Step 6": "الخطوة 6",
    "Confirm import": "تأكيد الاستيراد",
    "Restrova writes only accepted rows after this explicit confirmation.":
      "يحفظ Restrova الصفوف المقبولة فقط بعد هذا التأكيد الصريح.",
    Accepted: "مقبول",
    "Import job": "عملية الاستيراد",
    "Cancel import": "إلغاء الاستيراد",
    Cancelled: "ملغى",
    Completed: "مكتمل",
    "Import cancelled": "تم إلغاء الاستيراد",
    "Import completed": "اكتمل الاستيراد",
    "No staged data was written. You can start another import whenever you are ready.":
      "لم تُحفظ أي بيانات مرحلية. يمكنك بدء استيراد آخر عندما تكون جاهزًا.",
    "rows were imported successfully.": "صفوف تم استيرادها بنجاح.",
    "Import another file": "استيراد ملف آخر",
    Job: "عملية",
    "Loading import templates...": "جارٍ تحميل نماذج الاستيراد…",
    "Unable to complete the import request.": "تعذّر إكمال طلب الاستيراد.",
    accepted: "مقبول",
    duplicate: "مكرر",
    rejected: "مرفوض",
    "Automatic evaluation": "تقييم تلقائي",
    "Dataset quality summary": "ملخص جودة الملف",
    "The file is ready to import after you review the results.": "الملف جاهز للاستيراد بعد مراجعة النتائج.",
    "The file was analyzed, but it is an analytical dataset rather than a complete POS transaction log, so it will not be saved as inaccurate operational data.":
      "تم تحليل الملف، لكنه مجموعة بيانات تحليلية وليس سجل طلبات POS كاملًا؛ لن نحفظه كمعاملات تشغيلية غير دقيقة.",
    "Import ready": "جاهز للاستيراد",
    "Analysis only": "تحليل فقط",
    Rows: "الصفوف",
    Columns: "الأعمدة",
    Completeness: "اكتمال البيانات",
    "Duplicate rows": "صفوف مكررة",
    "View detailed statistics (optional)": "عرض الإحصاءات التفصيلية (اختياري)",
    Minimum: "أقل قيمة",
    Average: "المتوسط",
    Maximum: "أعلى قيمة",
    "File analysis complete": "اكتمل تحليل الملف",
    "Continue to the decision center or analyze another file.": "يمكنك الآن العودة إلى مركز القرار أو تحليل ملف آخر.",
    "Continue to decision center": "الانتقال إلى مركز القرار",
    "Analyze another file": "تحليل ملف آخر",
    "Columns matched automatically": "تمت مطابقة الأعمدة تلقائيًا",
    "View or edit mapping (optional)": "عرض أو تعديل المطابقة (اختياري)",
    Branches: "الفروع",
    Menu: "القائمة",
    Costs: "التكاليف",
    Sales: "المبيعات",
    "Create or update restaurant branches before importing menu, costs, or sales.":
      "أنشئ فروع المطعم أو حدّثها قبل استيراد القائمة أو التكاليف أو المبيعات.",
    "Define menu items and selling prices. Cost history is imported separately through the costs template.":
      "حدد أصناف القائمة وأسعار البيع. يُستورد سجل التكاليف بشكل منفصل عبر نموذج التكاليف.",
    "Define effective-dated direct food and packaging costs for menu items.":
      "حدد تكاليف المكونات والتغليف المباشرة للأصناف مع تاريخ سريانها.",
    "Import item-level sales rows with stable external identifiers for duplicate prevention and deterministic financial calculations.":
      "استورد مبيعات الأصناف بمعرّفات خارجية ثابتة لمنع التكرار وضمان حسابات مالية متسقة."
  },
  "zh-CN": {
    "Safe staged import": "安全分阶段导入",
    "Import restaurant data": "导入餐厅数据",
    "Validate, map and preview CSV/XLSX data before anything is written to your restaurant.":
      "在写入餐厅数据前，验证、匹配并预览 CSV/XLSX 数据。",
    "Import progress": "导入进度",
    Upload: "上传",
    Detection: "识别",
    Mapping: "列匹配",
    Validation: "验证",
    Preview: "预览",
    Confirm: "确认",
    Selected: "已选择",
    Choose: "选择",
    Template: "模板",
    required: "必填",
    optional: "可选",
    "Smart import": "智能导入",
    "Automatic detection": "自动识别",
    "CSV or XLSX file": "CSV 或 XLSX 文件",
    File: "文件",
    "High confidence": "高可信度",
    "Review suggested": "建议复核",
    Confirmed: "已确认",
    "Step 2 · File detected": "第 2 步 · 已识别文件",
    "Restrova classified this as": "Restrova 将此文件识别为",
    " data and evaluated the uploaded rows.": "数据，并评估了上传的行。",
    "Step 3": "第 3 步",
    "Review column mapping": "复核列匹配",
    "Map each uploaded column to a Restrova field. Required fields must be mapped before validation can continue.":
      "将上传的每列匹配到 Restrova 字段。必须匹配必填字段才能继续验证。",
    "Mapping complete": "匹配完成",
    "required missing": "个必填字段未匹配",
    "Uploaded column": "上传的列",
    "Restrova field": "Restrova 字段",
    Status: "状态",
    Map: "匹配",
    "Ignore column": "忽略此列",
    Mapped: "已匹配",
    Unmapped: "未匹配",
    "Save mapping & validate": "保存匹配并验证",
    "Warnings do not necessarily block confirmation.": "警告不一定阻止确认。",
    "Fix these rows and upload again before confirming.": "确认前请修正这些行并重新上传。",
    Row: "行",
    Column: "列",
    Value: "值",
    Message: "消息",
    "Step 4": "第 4 步",
    "Validation results": "验证结果",
    "Review accepted, rejected, duplicate and warning counts before confirming the import.":
      "确认导入前，请复核已接受、被拒绝、重复的行数及警告数。",
    "Ready to confirm": "可以确认",
    "Action required": "需要处理",
    "Total rows": "总行数",
    Valid: "有效",
    Invalid: "无效",
    Duplicates: "重复项",
    Warnings: "警告",
    "Blocking errors": "阻止导入的错误",
    "Unmapped optional columns": "未匹配的可选列",
    "These columns will be ignored unless you map them manually.": "若未手动匹配，这些列将被忽略。",
    "Step 5": "第 5 步",
    "Showing up to 20 rows using the original uploaded column names.": "使用上传文件的原始列名显示最多 20 行。",
    "Safe to import": "可以安全导入",
    Blocked: "已阻止",
    "Step 6": "第 6 步",
    "Confirm import": "确认导入",
    "Restrova writes only accepted rows after this explicit confirmation.":
      "只有在明确确认后，Restrova 才会写入已接受的行。",
    Accepted: "已接受",
    "Import job": "导入任务",
    "Cancel import": "取消导入",
    Cancelled: "已取消",
    Completed: "已完成",
    "Import cancelled": "导入已取消",
    "Import completed": "导入完成",
    "No staged data was written. You can start another import whenever you are ready.":
      "未写入任何暂存数据。准备好后可开始另一次导入。",
    "rows were imported successfully.": "行已成功导入。",
    "Import another file": "导入另一个文件",
    Job: "任务",
    "Loading import templates...": "正在加载导入模板…",
    "Unable to complete the import request.": "无法完成导入请求。",
    accepted: "已接受",
    duplicate: "重复",
    rejected: "已拒绝",
    "Automatic evaluation": "自动评估",
    "Dataset quality summary": "数据质量摘要",
    "The file is ready to import after you review the results.": "复核结果后即可导入此文件。",
    "The file was analyzed, but it is an analytical dataset rather than a complete POS transaction log, so it will not be saved as inaccurate operational data.":
      "已分析文件，但它是分析数据集而非完整的 POS 交易日志，因此不会将其保存为不准确的运营数据。",
    "Import ready": "可以导入",
    "Analysis only": "仅分析",
    Rows: "行数",
    Columns: "列数",
    Completeness: "完整度",
    "Duplicate rows": "重复行",
    "View detailed statistics (optional)": "查看详细统计（可选）",
    Minimum: "最小值",
    Average: "平均值",
    Maximum: "最大值",
    "File analysis complete": "文件分析完成",
    "Continue to the decision center or analyze another file.": "前往决策中心或分析另一个文件。",
    "Continue to decision center": "前往决策中心",
    "Analyze another file": "分析另一个文件",
    "Columns matched automatically": "已自动匹配列",
    "View or edit mapping (optional)": "查看或编辑匹配（可选）",
    Branches: "分店",
    Menu: "菜单",
    Costs: "成本",
    Sales: "销售",
    "Create or update restaurant branches before importing menu, costs, or sales.":
      "导入菜单、成本或销售前，请创建或更新餐厅分店。",
    "Define menu items and selling prices. Cost history is imported separately through the costs template.":
      "定义菜品和售价。成本历史通过成本模板单独导入。",
    "Define effective-dated direct food and packaging costs for menu items.":
      "定义带生效日期的菜品直接食材及包装成本。",
    "Import item-level sales rows with stable external identifiers for duplicate prevention and deterministic financial calculations.":
      "使用稳定的外部标识导入逐项销售记录，以防止重复并确保财务计算一致。"
  }
};

export function useImportText() {
  const { locale } = useLocale();
  return (text) => importTranslations[locale]?.[text] || text;
}
