export const intelligenceCopy = {
  ar: {
    title: "مركز التنبيهات",
    intro: "تابع التنبيهات وأدلتها، وحدد المسؤول والخطوة التالية.",
    refresh: "فحص البيانات",
    open: "مفتوحة",
    resolved: "تم حلها",
    all: "الكل",
    empty: "ما فيه تنبيهات ضمن هذا العرض. افحص البيانات وتأكد من اكتمالها.",
    loading: "جارٍ التحميل…",
    error: "تعذر إكمال الطلب. حاول مرة ثانية.",
    retry: "إعادة المحاولة",
    preferences: "إعدادات التنبيهات",
    save: "حفظ الإعدادات",
    saved: "تم الحفظ",
    types: "أنواع التنبيهات",
    branches: "الفروع",
    frequency: "تكرار الإشعارات",
    off: "متوقفة",
    immediate: "مرة لكل تنبيه",
    daily: "يوميًا",
    weekly: "أسبوعيًا",
    channels: "قنوات الإشعارات",
    unavailable: "غير مفعّلة",
    evidence: "الأدلة",
    current: "الفترة الحالية",
    previous: "فترة المقارنة",
    revenue: "صافي المبيعات",
    gross: "إجمالي المبيعات",
    orders: "الطلبات",
    threshold: "الحد المحدد",
    measured: "القيمة المرصودة",
    sources: "السجلات المصدرية",
    resolve: "تم الحل",
    reopen: "إعادة فتح",
    comment: "تعليق المتابعة",
    addComment: "إضافة تعليق",
    assign: "إسناد",
    unassigned: "بدون مسؤول",
    history: "سجل المتابعة",
    recurrence: "مرات الظهور السابقة",
    more: "عرض الأقدم",
    checked: "نتائج الفحص",
    insufficient: "بيانات غير كافية",
    noTrigger: "لم يتجاوز الحد",
    triggered: "تجاوز الحد",
    scope: "نطاق العرض",
    restaurant: "المطعم",
    branch: "الفرع المحدد",
    organization: "المجموعة",
    allBranches: "كل الفروع المسموح بها",
    phone: "رقم واتساب",
    consent: "أوافق على استلام تنبيهات واتساب على هذا الرقم",
    device: "تفعيل الإشعارات لهذا الجهاز",
    pushReady: "الجهاز جاهز. احفظ الإعدادات لتفعيل الاشتراك.",
    queue: "جدولة إشعاراتي",
    delivery: "حالة الإشعارات",
    forecast: "توقعات الأداء",
    tomorrow: "الغد",
    seven: "7 أيام",
    thirty: "30 يومًا",
    horizon: "فترة التوقع",
    assumption: "تقديرات من السجل المستورد وليست نتائج مضمونة. البيانات الناقصة لا تُحسب صفرًا.",
    noData: "غير متاح",
    food: "تكلفة الطعام",
    packaging: "التغليف",
    commissions: "العمولات",
    operating: "تكاليف التشغيل",
    grossProfit: "إجمالي الربح",
    contribution: "الربح بعد التكاليف المتغيرة",
    netProfit: "صافي الربح",
    date: "التاريخ",
    historyDays: "أيام السجل",
    percentage: "نقطة أساس (100 = نقطة مئوية)",
    INFO: "معلومة",
    WARNING: "تحذير",
    CRITICAL: "حرج",
    created: "إنشاء",
    pending: "بالانتظار",
    sending: "جارٍ الإرسال",
    sent: "قبله مزود الخدمة",
    failed: "تعذر الإرسال",
    cancelled: "أُلغي",
    email: "البريد الإلكتروني",
    push: "إشعار الجهاز",
    whatsapp: "واتساب",
    slack: "Slack",
    teams: "Teams"
  },
  en: {
    title: "Alert center",
    intro: "Review evidence, assign ownership and track the next action.",
    refresh: "Evaluate data",
    open: "Open",
    resolved: "Resolved",
    all: "All",
    empty: "No alerts in this view. Evaluate the data and check completeness.",
    loading: "Loading…",
    error: "Unable to complete the request. Please try again.",
    retry: "Retry",
    preferences: "Alert preferences",
    save: "Save preferences",
    saved: "Saved",
    types: "Alert types",
    branches: "Branches",
    frequency: "Notification frequency",
    off: "Off",
    immediate: "Once per alert",
    daily: "Daily",
    weekly: "Weekly",
    channels: "Notification channels",
    unavailable: "Not configured",
    evidence: "Evidence",
    current: "Current period",
    previous: "Comparison period",
    revenue: "Net sales",
    gross: "Gross sales",
    orders: "Orders",
    threshold: "Threshold",
    measured: "Observed value",
    sources: "Source records",
    resolve: "Resolve",
    reopen: "Reopen",
    comment: "Follow-up comment",
    addComment: "Add comment",
    assign: "Assign",
    unassigned: "Unassigned",
    history: "Activity history",
    recurrence: "Previous occurrences",
    more: "Load older",
    checked: "Evaluation results",
    insufficient: "Insufficient data",
    noTrigger: "Below threshold",
    triggered: "Triggered",
    scope: "Scope",
    restaurant: "Restaurant",
    branch: "Selected branch",
    organization: "Group",
    allBranches: "All authorized branches",
    phone: "WhatsApp number",
    consent: "I consent to WhatsApp alerts at this number",
    device: "Enable notifications on this device",
    pushReady: "Device ready. Save preferences to activate the subscription.",
    queue: "Queue my notifications",
    delivery: "Notification status",
    forecast: "Operating forecast",
    tomorrow: "Tomorrow",
    seven: "7 days",
    thirty: "30 days",
    horizon: "Forecast horizon",
    assumption: "Estimates from imported history, not guarantees. Missing data is never treated as zero.",
    noData: "Unavailable",
    food: "Food costs",
    packaging: "Packaging",
    commissions: "Commissions",
    operating: "Operating costs",
    grossProfit: "Gross profit",
    contribution: "Contribution profit",
    netProfit: "Net profit",
    date: "Date",
    historyDays: "History days",
    percentage: "Basis points (100 = 1 percentage point)",
    INFO: "Info",
    WARNING: "Warning",
    CRITICAL: "Critical",
    created: "Created",
    pending: "Pending",
    sending: "Sending",
    sent: "Accepted by provider",
    failed: "Failed",
    cancelled: "Cancelled",
    email: "Email",
    push: "Device push",
    whatsapp: "WhatsApp",
    slack: "Slack",
    teams: "Teams"
  },
  zh: {
    title: "预警中心",
    intro: "核查依据、分配负责人并跟踪后续处理。",
    refresh: "评估数据",
    open: "待处理",
    resolved: "已解决",
    all: "全部",
    empty: "此视图没有预警。请评估数据并检查完整性。",
    loading: "加载中…",
    error: "请求未完成，请重试。",
    retry: "重试",
    preferences: "预警偏好",
    save: "保存设置",
    saved: "已保存",
    types: "预警类型",
    branches: "分店",
    frequency: "通知频率",
    off: "关闭",
    immediate: "每条预警一次",
    daily: "每天",
    weekly: "每周",
    channels: "通知渠道",
    unavailable: "未配置",
    evidence: "依据",
    current: "本期",
    previous: "对比期",
    revenue: "净销售额",
    gross: "销售总额",
    orders: "订单",
    threshold: "阈值",
    measured: "观测值",
    sources: "来源记录",
    resolve: "标记解决",
    reopen: "重新打开",
    comment: "跟进备注",
    addComment: "添加备注",
    assign: "分配",
    unassigned: "未分配",
    history: "处理记录",
    recurrence: "此前出现次数",
    more: "加载更早记录",
    checked: "评估结果",
    insufficient: "数据不足",
    noTrigger: "未超过阈值",
    triggered: "已触发",
    scope: "范围",
    restaurant: "餐厅",
    branch: "所选分店",
    organization: "集团",
    allBranches: "所有有权访问的分店",
    phone: "WhatsApp号码",
    consent: "我同意在此号码接收WhatsApp预警",
    device: "在此设备启用通知",
    pushReady: "设备已就绪。保存设置以启用订阅。",
    queue: "将我的通知加入队列",
    delivery: "通知状态",
    forecast: "经营预测",
    tomorrow: "明天",
    seven: "7天",
    thirty: "30天",
    horizon: "预测周期",
    assumption: "根据导入历史估算，并非保证。缺失数据不会按零处理。",
    noData: "不可用",
    food: "食材成本",
    packaging: "包装",
    commissions: "佣金",
    operating: "运营成本",
    grossProfit: "毛利润",
    contribution: "边际贡献",
    netProfit: "净利润",
    date: "日期",
    historyDays: "历史天数",
    percentage: "基点（100 = 1个百分点）",
    INFO: "信息",
    WARNING: "警告",
    CRITICAL: "严重",
    created: "创建",
    pending: "等待中",
    sending: "发送中",
    sent: "服务商已接受",
    failed: "失败",
    cancelled: "已取消",
    email: "电子邮件",
    push: "设备推送",
    whatsapp: "WhatsApp",
    slack: "Slack",
    teams: "Teams"
  }
};
export const ruleLabels = {
  ar: ["تكلفة الطعام", "هبوط المبيعات", "هبوط هامش الربح", "زيادة المرتجعات", "زيادة الخصومات", "مبيعات غير معتادة"],
  en: ["Food cost", "Sales decline", "Margin decline", "Refund increase", "Discount increase", "Unusual sales"],
  zh: ["食材成本", "销售额下降", "利润率下降", "退款增加", "折扣增加", "异常销售"]
};
export const ruleTypes = [
  "food_cost_above_target",
  "sales_drop",
  "profit_margin_drop",
  "refund_rate_increase",
  "discount_rate_increase",
  "sales_outlier"
];
export const thresholdKeys = [
  "foodCostTargetBps",
  "salesDropBps",
  "profitMarginDropBps",
  "refundRateIncreaseBps",
  "discountRateIncreaseBps"
];
export const reviewActions = {
  ar: [
    "راجع تكلفة المكونات والهدر والحصص مقابل الحد المحدد قبل ما تعتمد أي تغيير.",
    "راجع الأصناف وقنوات الطلب وتأكد من اكتمال الاستيراد قبل ما تحدد السبب.",
    "راجع بنود التكاليف والخصومات والمرتجعات في الفترتين.",
    "راجع أسباب المرتجعات المسجلة مع الفريق وابدأ بالمشكلات المتكررة.",
    "راجع العروض وصلاحيات الخصم مقابل الخطة المعتمدة.",
    "قارن مبيعات اليوم بنفس يوم الأسبوع وتأكد من اكتمال البيانات."
  ],
  en: [
    "Review ingredient costs, waste and portions against the configured target before making changes.",
    "Review items and order channels and verify import completeness before identifying a cause.",
    "Review costs, discounts and refunds in both periods.",
    "Review recorded refund reasons with the team, starting with recurring issues.",
    "Review promotions and discount permissions against the approved plan.",
    "Compare the day's sales with the same weekday and verify data completeness."
  ],
  zh: [
    "对照设定目标检查食材成本、损耗和份量，再决定是否调整。",
    "检查菜品和订单渠道，并在判断原因前确认导入数据完整性。",
    "核查两个期间的成本、折扣和退款。",
    "与团队检查记录的退款原因，优先处理重复问题。",
    "对照已批准的计划检查促销和折扣权限。",
    "与相同星期几的销售额比较，并核查数据完整性。"
  ]
};
