export const integrationCopy = {
  ar: {
    title: "مصادر البيانات",
    intro: "اربط ملفات الأنظمة الخارجية ببيانات مطعمك، واحفظ ربط الأعمدة للاستيراد التالي.",
    owner: "إدارة المصادر متاحة لمالك المطعم.",
    imports: "استيراد البيانات",
    name: "اسم المصدر",
    type: "نوع البيانات",
    sales: "مبيعات",
    menu: "أصناف",
    costs: "تكاليف",
    branches: "فروع",
    create: "إضافة مصدر",
    source: "المصدر",
    select: "اختر مصدرًا",
    fileMode: "استيراد ملفات CSV يدويًا؛ هذا المصدر غير متصل بخدمة خارجية مباشرة.",
    upload: "رفع ملف CSV",
    loading: "جاري التحقق…",
    error: "تعذّر إكمال العملية. تحقق من الملف وربط الأعمدة والصلاحيات ثم حاول مرة ثانية.",
    preview: "مراجعة البيانات",
    accepted: "المقبولة",
    rejected: "المرفوضة",
    duplicates: "المكررة",
    column: "عمود الملف",
    target: "الحقل المقابل",
    skip: "تجاهل",
    map: "حفظ الربط وإعادة التحقق",
    confirm: "تأكيد إدخال البيانات",
    done: "تم ربط البيانات بالتقارير والمساعد.",
    history: "سجل الاستيراد",
    preview_ready: "بانتظار المراجعة",
    confirmed: "تم التأكيد",
    cancelled: "ملغي"
  },
  en: {
    title: "Data sources",
    intro: "Map external system exports into restaurant data and reuse column mappings on the next import.",
    owner: "Only restaurant owners can manage sources.",
    imports: "Import data",
    name: "Source name",
    type: "Data type",
    sales: "Sales",
    menu: "Menu",
    costs: "Costs",
    branches: "Branches",
    create: "Add source",
    source: "Source",
    select: "Choose a source",
    fileMode: "Manual CSV import; this source is not connected to an external service.",
    upload: "Upload CSV",
    loading: "Validating…",
    error: "Unable to complete the operation. Check the file, column mappings and permissions, then retry.",
    preview: "Review data",
    accepted: "Accepted",
    rejected: "Rejected",
    duplicates: "Duplicates",
    column: "File column",
    target: "Target field",
    skip: "Ignore",
    map: "Save mapping and validate",
    confirm: "Confirm data import",
    done: "Data is connected to reports and the copilot.",
    history: "Import history",
    preview_ready: "Awaiting review",
    confirmed: "Confirmed",
    cancelled: "Cancelled"
  },
  zh: {
    title: "数据来源",
    intro: "将外部系统导出的文件映射到餐厅数据，并在下次导入时复用列映射。",
    owner: "仅餐厅所有者可管理来源。",
    imports: "导入数据",
    name: "来源名称",
    type: "数据类型",
    sales: "销售",
    menu: "菜品",
    costs: "成本",
    branches: "门店",
    create: "添加来源",
    source: "来源",
    select: "选择来源",
    fileMode: "手动 CSV 导入；此来源未直接连接外部服务。",
    upload: "上传 CSV",
    loading: "正在验证…",
    error: "操作失败，请检查文件、列映射和权限后重试。",
    preview: "审核数据",
    accepted: "接受",
    rejected: "拒绝",
    duplicates: "重复",
    column: "文件列",
    target: "目标字段",
    skip: "忽略",
    map: "保存映射并验证",
    confirm: "确认导入数据",
    done: "数据已连接到报告和智能助手。",
    history: "导入历史",
    preview_ready: "等待审核",
    confirmed: "已确认",
    cancelled: "已取消"
  }
};
