export const operationsCopy = {
  ar: {
    title: "أداء الفروع والمبيعات",
    description: "قارن الأداء، وافهم أوقات الطلب وقنوات البيع من بياناتك المسجلة.",
    overview: "الفروع والفرص",
    time: "الأيام والساعات",
    channels: "قنوات البيع",
    custom: "فترة محددة",
    from: "من تاريخ",
    to: "إلى تاريخ",
    importedRevenue: "صافي المبيعات المستوردة",
    orders: "الطلبات المسجلة",
    comparable: "فروع قابلة للمقارنة",
    growth: "نمو الفروع المتطابقة",
    sameStore: "مقارنة الفروع المتطابقة",
    matched: "أيام متطابقة في كل فترة",
    comparisonHelp:
      "نوازن عدد أيام الأسبوع، ونستبعد الأيام غير المكتملة والفروع التي لا تملك سجل افتتاح وبيانات لكل يوم مقارن.",
    excluded: "فروع مستبعدة من المقارنة",
    noComparable: "البيانات الحالية لا تكفي لمقارنة عادلة. راجع تواريخ افتتاح الفروع واستورد بيانات الفترتين.",
    scorecards: "مؤشرات الفروع",
    branch: "الفرع",
    revenue: "صافي المبيعات",
    costs: "إجمالي التكاليف",
    profit: "الربح التشغيلي",
    margin: "هامش الربح",
    change: "التغير",
    evidence: "مصدر الأرقام",
    unavailable: "غير متوفر",
    scorecardHelp:
      "المؤشرات من السجل المالي؛ تبقى الأرباح والتكاليف غير متوفرة عند نقص فئاتها. التغيرات أدناه تظهر فقط للفترات الكاملة والمتطابقة.",
    opportunities: "فرص تستحق المراجعة",
    noOpportunities: "لا توجد إشارات تتجاوز الحدود المحددة ضمن الفروع القابلة للمقارنة.",
    weekdays: "المبيعات حسب اليوم",
    hours: "المبيعات حسب الساعة",
    dayparts: "فترات اليوم",
    timeHelp: "الأوقات حسب المنطقة الزمنية للمطعم. الأرقام تخص المبيعات المستوردة خلال الفترة المختارة.",
    sourceHelp: "السجلات بلا تكلفة كاملة لا تثبت الربح. غياب مبيعات يوم معيّن لا يعني أن مبيعاته صفر.",
    channel: "القناة",
    refunds: "المرتجعات",
    discounts: "الخصومات",
    commission: "العمولة",
    afterCommission: "الإيراد بعد العمولة",
    platforms: "منصات التوصيل",
    channelHelp: "الإيراد بعد العمولة لا يمثل الربح. يُصنف التوصيل كمنصة فقط عند وجود اسم المنصة في الملف المستورد.",
    noData: "لا توجد مبيعات مستوردة لهذه الفترة",
    retry: "إعادة المحاولة",
    error: "تعذر تحميل التحليل. حاول مرة أخرى.",
    loading: "جارٍ تحميل تحليل الفروع…",
    dates: "تواريخ المقارنة",
    current: "الفترة الحالية",
    previous: "فترة المقارنة",
    recorded: "السجلات المصدرية",
    dateError: "اختر تاريخ البداية والنهاية بترتيب صحيح.",
    reasons: {
      comparison_disabled: "المقارنة معطلة",
      no_matching_completed_days: "لا توجد أيام مكتملة ومتطابقة",
      opening_date_unknown: "تاريخ الافتتاح غير مسجل",
      opened_during_or_after_comparison: "الفرع جديد خلال الفترة",
      closed_before_period_end: "أغلق الفرع قبل نهاية الفترة",
      missing_current_sales_days: "مبيعات بعض أيام الفترة الحالية ناقصة",
      missing_comparison_sales_days: "مبيعات بعض أيام المقارنة ناقصة"
    },
    types: {
      falling_sales: ["تراجع المبيعات", "راجع الأيام والأصناف التي تراجعت، وجرّب إجراءً محدودًا ثم قِس أثره."],
      high_refunds: ["ارتفاع المرتجعات", "راجع الطلبات المرتجعة وأسبابها مع الفريق قبل تحديد الإجراء المناسب."],
      abnormal_discounts: [
        "زيادة الخصومات",
        "راجع صلاحيات الخصم ونتائج العروض، وتأكد أن الزيادة مدعومة بمبيعات إضافية."
      ],
      underperformance: [
        "نمو أقل من الفروع المقارنة",
        "قارن التوفر والتشغيل والعروض مع الفروع الأخرى؛ هذا فرق أداء ولا يثبت سببه."
      ],
      rising_costs: [
        "ارتفاع نسبة تكلفة الطعام",
        "راجع أسعار التوريد وكميات الوصفات والهدر المسجل، ثم تحقق من وفر أي تغيير."
      ]
    },
    channelNames: { dine_in: "داخل المطعم", takeaway: "سفري", delivery: "توصيل مباشر", aggregator: "منصات التوصيل" },
    daypartNames: {
      breakfast: "الفطور · 05–12",
      lunch: "الغداء · 12–17",
      dinner: "العشاء · 17–22",
      late_night: "آخر الليل · 22–05"
    }
  },
  en: {
    title: "Branch and sales performance",
    description: "Compare branches and understand demand by time and channel using recorded evidence.",
    overview: "Branches and opportunities",
    time: "Days and hours",
    channels: "Sales channels",
    custom: "Custom dates",
    from: "From date",
    to: "To date",
    importedRevenue: "Imported net sales",
    orders: "Recorded orders",
    comparable: "Comparable branches",
    growth: "Same-store sales growth",
    sameStore: "Same-store comparison",
    matched: "matched days in each period",
    comparisonHelp:
      "We match weekday counts and exclude incomplete days and branches without opening dates or sales evidence on every matched day.",
    excluded: "Excluded branches",
    noComparable: "There is not enough evidence for a fair comparison. Review opening dates and import both periods.",
    scorecards: "Branch scorecards",
    branch: "Branch",
    revenue: "Net sales",
    costs: "Total costs",
    profit: "Operating profit",
    margin: "Profit margin",
    change: "Change",
    evidence: "Source evidence",
    unavailable: "Unavailable",
    scorecardHelp:
      "Scorecards use the financial ledger. Missing categories keep costs and profit unavailable. Changes below appear only for complete, aligned periods.",
    opportunities: "Opportunities to review",
    noOpportunities: "No signals exceed the documented thresholds among comparable branches.",
    weekdays: "Sales by weekday",
    hours: "Sales by hour",
    dayparts: "Dayparts",
    timeHelp: "Times use the restaurant timezone. Values cover imported sales in the selected period.",
    sourceHelp:
      "Incomplete cost records do not establish profit. A day without recorded sales is not proof of zero sales.",
    channel: "Channel",
    refunds: "Refunds",
    discounts: "Discounts",
    commission: "Commission",
    afterCommission: "Revenue after commission",
    platforms: "Delivery platforms",
    channelHelp:
      "Revenue after commission is not profit. Delivery is classified as an aggregator only when an imported platform name is present.",
    noData: "No imported sales in this period",
    retry: "Try again",
    error: "Unable to load this analysis. Please try again.",
    loading: "Loading branch analysis…",
    dates: "Comparison dates",
    current: "Current period",
    previous: "Comparison period",
    recorded: "Source records",
    dateError: "Select a valid start and end date in order.",
    reasons: {
      comparison_disabled: "Comparison disabled",
      no_matching_completed_days: "No matching completed days",
      opening_date_unknown: "Opening date not recorded",
      opened_during_or_after_comparison: "Opened during the comparison period",
      closed_before_period_end: "Closed before the period ended",
      missing_current_sales_days: "Missing current sales dates",
      missing_comparison_sales_days: "Missing comparison sales dates"
    },
    types: {
      falling_sales: [
        "Sales are falling",
        "Review declining days and items, try a bounded action, and measure its effect."
      ],
      high_refunds: [
        "High refunds",
        "Review refunded orders and their reasons with the team before choosing an action."
      ],
      abnormal_discounts: [
        "Discounts are rising",
        "Review discount permissions and promotion results to check whether discounts bring additional sales."
      ],
      underperformance: [
        "Growth below comparable peers",
        "Compare availability, operations and promotions with peer branches. The gap does not establish a cause."
      ],
      rising_costs: [
        "Food cost ratio is rising",
        "Review supplier prices, recipe quantities and recorded waste, then verify savings from any change."
      ]
    },
    channelNames: { dine_in: "Dine-in", takeaway: "Takeaway", delivery: "Direct delivery", aggregator: "Aggregators" },
    daypartNames: {
      breakfast: "Breakfast · 05–12",
      lunch: "Lunch · 12–17",
      dinner: "Dinner · 17–22",
      late_night: "Late night · 22–05"
    }
  },
  "zh-CN": {
    title: "分店与销售表现",
    description: "根据已记录的数据比较分店，并分析不同时段和销售渠道。",
    overview: "分店与改进机会",
    time: "日期与时段",
    channels: "销售渠道",
    custom: "自定义日期",
    from: "开始日期",
    to: "结束日期",
    importedRevenue: "已导入净销售额",
    orders: "已记录订单",
    comparable: "可比较分店",
    growth: "同店销售增长",
    sameStore: "同店比较",
    matched: "每个期间匹配的天数",
    comparisonHelp: "匹配相同的星期天数；排除未结束的日期，以及缺少开业日期或任一匹配日销售记录的分店。",
    excluded: "排除的分店",
    noComparable: "数据不足，无法公平比较。请检查开业日期并导入两个期间的数据。",
    scorecards: "分店指标",
    branch: "分店",
    revenue: "净销售额",
    costs: "总成本",
    profit: "营业利润",
    margin: "利润率",
    change: "变化",
    evidence: "数据来源",
    unavailable: "暂无数据",
    scorecardHelp: "指标来自财务账本；缺少相关类别时不显示成本或利润。仅对完整且匹配的期间显示变化。",
    opportunities: "待评估的改进机会",
    noOpportunities: "可比较分店中没有超过所设阈值的信号。",
    weekdays: "按星期分析",
    hours: "按小时分析",
    dayparts: "用餐时段",
    timeHelp: "时间使用餐厅时区。数值仅包含选定期间的已导入销售记录。",
    sourceHelp: "成本记录不完整时无法确认利润。没有某天的销售记录并不代表销售额为零。",
    channel: "渠道",
    refunds: "退款",
    discounts: "折扣",
    commission: "佣金",
    afterCommission: "扣除佣金后收入",
    platforms: "外卖平台",
    channelHelp: "扣除佣金后收入并非利润。只有导入了平台名称的配送记录才归入外卖平台。",
    noData: "该期间没有导入销售数据",
    retry: "重试",
    error: "无法加载分析，请重试。",
    loading: "正在加载分店分析…",
    dates: "比较日期",
    current: "当前期间",
    previous: "比较期间",
    recorded: "来源记录",
    dateError: "请选择顺序正确的开始和结束日期。",
    reasons: {
      comparison_disabled: "比较已关闭",
      no_matching_completed_days: "没有完整匹配的日期",
      opening_date_unknown: "未记录开业日期",
      opened_during_or_after_comparison: "比较期间内新开业",
      closed_before_period_end: "在期间结束前关闭",
      missing_current_sales_days: "当前期间缺少销售日期",
      missing_comparison_sales_days: "比较期间缺少销售日期"
    },
    types: {
      falling_sales: ["销售下降", "检查下降的日期和菜品，进行小规模调整并衡量效果。"],
      high_refunds: ["退款偏高", "与团队核查退款订单及原因，再确定措施。"],
      abnormal_discounts: ["折扣增加", "核查折扣权限及促销结果，确认折扣是否带来额外销售。"],
      underperformance: ["增长低于同类分店", "比较供应、运营及促销；增长差距本身不能说明原因。"],
      rising_costs: ["食材成本比例上升", "检查采购价格、配方用量和已记录损耗，再验证调整带来的节省。"]
    },
    channelNames: { dine_in: "堂食", takeaway: "自取", delivery: "直接配送", aggregator: "外卖平台" },
    daypartNames: {
      breakfast: "早餐 · 05–12",
      lunch: "午餐 · 12–17",
      dinner: "晚餐 · 17–22",
      late_night: "深夜 · 22–05"
    }
  }
};
