export const ownerCopy = {
  en: {
    title: "Your restaurant, at a glance",
    intro: "Yesterday’s recorded results, the changes that matter, and your next steps.",
    health: "How are we doing?",
    changed: "What changed?",
    why: "What explains the change?",
    next: "What should we do?",
    evidence: "Review the evidence",
    missing: "More complete data is needed. Import the missing records before making a decision.",
    recorded: "Based on confirmed imports and recorded entries. External POS connections are not live.",
    today: "Today so far",
    profit: "Profit analysis",
    todayIntro:
      "Recorded results through now, compared with the same local time. Refreshes every minute while this page is visible.",
    asOf: "Calculated at",
    previous: "Comparison cutoff",
    waterfall: "From revenue to operating profit",
    waterfallHint:
      "Revenue less recorded costs. Profit is withheld when inputs are incomplete; tax, interest and depreciation are excluded.",
    total: "Running balance",
    unknown: "Unavailable",
    priority: "Priority order",
    recent: "Newest first",
    urgent: "Highest severity first",
    drill: "View branch",
    menuNext: "Review menu recommendations",
    scopeNote: "Choose a branch in the top bar to review its recommendations.",
    dateError: "Choose both dates in chronological order.",
    busy: "Preparing an evidence-backed answer…"
  },
  ar: {
    title: "مطعمك بنظرة واضحة",
    intro: "نتائج أمس المسجلة، أهم التغيّرات، وخطوتك الجاية.",
    health: "كيف وضع المطعم؟",
    changed: "وش تغيّر؟",
    why: "وش يفسّر التغيّر؟",
    next: "وش نسوي بعدها؟",
    evidence: "راجع الأدلة",
    missing: "نحتاج بيانات أكمل. استورد السجلات الناقصة قبل ما تعتمد القرار.",
    recorded: "مبني على الاستيرادات المؤكدة والسجلات المدخلة. الربط المباشر مع أنظمة الكاشير غير مفعّل.",
    today: "اليوم حتى الآن",
    profit: "تحليل الأرباح",
    todayIntro: "النتائج المسجلة حتى الآن مقارنة بنفس التوقيت المحلي. تتحدث كل دقيقة أثناء عرض الصفحة.",
    asOf: "وقت الحساب",
    previous: "نهاية فترة المقارنة",
    waterfall: "من الإيراد إلى الربح التشغيلي",
    waterfallHint:
      "الإيراد ناقص التكاليف المسجلة. ما نعرض الربح إذا البيانات ناقصة؛ الضريبة والفوائد والإهلاك غير مشمولة.",
    total: "الرصيد المتبقي",
    unknown: "غير متاح",
    priority: "ترتيب الأولوية",
    recent: "الأحدث أولًا",
    urgent: "الأشد خطورة أولًا",
    drill: "عرض الفرع",
    menuNext: "راجع توصيات القائمة",
    scopeNote: "اختر الفرع من الشريط العلوي لمراجعة توصياته.",
    dateError: "اختر تاريخ البداية والنهاية بالترتيب الصحيح.",
    busy: "نجهّز إجابة مدعومة ببياناتك…"
  },
  "zh-CN": {
    title: "餐厅经营一目了然",
    intro: "查看昨日已记录的业绩、重要变化和下一步行动。",
    health: "经营情况如何？",
    changed: "有哪些变化？",
    why: "哪些数据解释了变化？",
    next: "下一步该做什么？",
    evidence: "查看依据",
    missing: "数据尚不完整。请先导入缺失记录，再作出决策。",
    recorded: "基于已确认的导入数据和录入记录。尚未实时连接外部收银系统。",
    today: "今日截至目前",
    profit: "利润分析",
    todayIntro: "比较截至当前本地时间的已记录业绩。页面可见时每分钟刷新一次。",
    asOf: "计算时间",
    previous: "对比截止时间",
    waterfall: "从营收到营业利润",
    waterfallHint: "营收减去已记录的成本。数据不完整时不显示利润；不包含税费、利息和折旧。",
    total: "剩余金额",
    unknown: "暂无数据",
    priority: "优先顺序",
    recent: "最新优先",
    urgent: "严重程度优先",
    drill: "查看分店",
    menuNext: "查看菜单建议",
    scopeNote: "请在顶部选择分店，查看该分店的建议。",
    dateError: "请选择起止日期，且结束日期不得早于开始日期。",
    busy: "正在生成有数据依据的回答…"
  }
};
