export const simpleCopy = {
  ar: {
    hello: "حيّاك",
    home: "كيف مطعمك اليوم؟",
    today: "اليوم حتى الآن",
    sales: "المبيعات",
    profit: "الربح التشغيلي",
    orders: "الطلبات",
    costs: "تكاليف الأصناف",
    unknown: "غير متوفر",
    ask: "اسأل Restrova AI",
    important: "يحتاج انتباهك",
    details: "عرض التفاصيل",
    forecast: "عرض التوقعات",
    reports: "التقارير والتصدير",
    welcome: "أهلًا بك في Restrova",
    connectIntro: "خلّنا نربط بيانات مطعمك ونطلع بأول تحليل.",
    connect: "ربط مصدر البيانات",
    connectionNote:
      "التكاملات المتاحة تظهر بحالتها الفعلية. المزامنة التلقائية تحتاج موصلًا مفعّلًا؛ الرفع اليدوي متاح الآن.",
    upload: "رفع Excel أو CSV",
    later: "بعدين",
    data: "بيانات مطعمك",
    dataIntro: "مصدر واحد للأرقام التي يستخدمها مساعدك.",
    ready: "توجد بيانات",
    missing: "بيانات ناقصة",
    updated: "آخر سجل",
    status: "حالة البيانات",
    manual: "إضافة يدويًا",
    settings: "الإعدادات",
    restaurant: "المطعم",
    branches: "الفروع",
    team: "الفريق",
    integrations: "التكاملات",
    language: "اللغة",
    account: "الحساب",
    insight: "الخطوة التالية",
    noAlert: "لا توجد تنبيهات مسجلة حاليًا. هذا لا يعني اكتمال كل البيانات.",
    viewMenu: "مراجعة الأصناف",
    manage: "إدارة",
    retry: "إعادة المحاولة",
    error: "تعذّر تحميل البيانات. أعد المحاولة.",
    loading: "جارٍ التحميل…",
    profitNote: "الأرباح غير متاحة عند نقص التكاليف. الأرقام الحالية جزئية وتتبع توقيت المطعم.",
    history: "المحادثات السابقة",
    tools: "المزيد من الخيارات",
    trend: "مبيعات آخر 7 أيام مكتملة",
    noTrend: "ارفع بيانات المبيعات لعرض الاتجاه.",
    readOnly: "حسابك للعرض فقط. يتولى المالك استيراد البيانات وربط المصادر.",
    saved: "تم حفظ البيانات",
    analyze: "عرض تحليل AI",
    manualNote:
      "أدخل مبالغ اليوم بعملة المطعم. التكلفة الإجمالية تشمل الهدر. الملخص اليدوي منفصل عن معاملات الاستيراد، ولا يُجمع معها.",
    waste: "الهدر (ضمن التكاليف)",
    save: "حفظ وتحليل",
    totalCosts: "إجمالي التكاليف",
    manualSource: "ملخص يدوي لليوم",
    manualConflict: "يوجد ملخص لهذا اليوم أو تغيّرت البيانات. حدّث الصفحة وراجع الإدخال.",
    manualDisabled: "الإدخال اليدوي يتطلب تحديد فرع.",
    manualExisting: "يوجد ملخص يدوي لهذا اليوم؛ لا يمكن إضافة ملخص ثانٍ.",
    manualUnavailable: "توجد مبيعات مستوردة اليوم؛ استخدم سجلات المصدر لتفادي تكرار الأرقام."
  },
  en: {
    hello: "Welcome",
    home: "How is your restaurant today?",
    today: "Today so far",
    sales: "Sales",
    profit: "Operating profit",
    orders: "Orders",
    costs: "Item costs",
    unknown: "Unavailable",
    ask: "Ask Restrova AI",
    important: "Needs your attention",
    details: "View details",
    forecast: "View forecast",
    reports: "Reports & export",
    welcome: "Welcome to Restrova",
    connectIntro: "Let's connect your restaurant and find your first insight.",
    connect: "Connect a data source",
    connectionNote:
      "Available integrations show their actual status. Automatic sync requires an enabled connector; file upload is available now.",
    upload: "Upload Excel / CSV",
    later: "I'll do this later",
    data: "Your restaurant data",
    dataIntro: "One source for the numbers your assistant uses.",
    ready: "Data available",
    missing: "Missing data",
    updated: "Latest record",
    status: "Data status",
    manual: "Add manually",
    settings: "Settings",
    restaurant: "Restaurant",
    branches: "Branches",
    team: "Team",
    integrations: "Integrations",
    language: "Language",
    account: "Account",
    insight: "Next best step",
    noAlert: "No recorded alerts right now. This does not mean every data source is complete.",
    viewMenu: "Review dishes",
    manage: "Manage",
    retry: "Retry",
    error: "Unable to load data. Please retry.",
    loading: "Loading…",
    profitNote:
      "Profit is unavailable when cost data is incomplete. Today's figures are partial and use the restaurant timezone.",
    history: "Previous conversations",
    tools: "More options",
    trend: "Sales over 7 completed days",
    noTrend: "Upload sales data to see the trend.",
    readOnly: "Your account has read-only access. The owner manages imports and connections.",
    saved: "Data saved",
    analyze: "See AI analysis",
    manualNote:
      "Enter today's amounts in your restaurant currency. Total costs include waste. This manual summary stays separate from imported transactions and is never added to them.",
    waste: "Waste (included in costs)",
    save: "Save & analyze",
    totalCosts: "Total costs",
    manualSource: "Manual daily summary",
    manualConflict: "A summary already exists or data changed. Refresh and review the entry.",
    manualDisabled: "Choose a branch for manual entry.",
    manualExisting: "A manual summary already exists for today; another cannot be added.",
    manualUnavailable: "Imported sales exist today. Use source records to avoid counting data twice."
  },
  "zh-CN": {
    hello: "欢迎",
    home: "今天餐厅经营得怎么样？",
    today: "今日截至目前",
    sales: "销售额",
    profit: "营业利润",
    orders: "订单",
    costs: "菜品成本",
    unknown: "暂无数据",
    ask: "询问 Restrova AI",
    important: "需要关注",
    details: "查看详情",
    forecast: "查看预测",
    reports: "报告与导出",
    welcome: "欢迎使用 Restrova",
    connectIntro: "连接餐厅数据，获取第一份分析。",
    connect: "连接数据源",
    connectionNote: "集成显示真实状态。自动同步需要已启用的连接器，目前可以上传文件。",
    upload: "上传 Excel / CSV",
    later: "稍后再说",
    data: "餐厅数据",
    dataIntro: "助手分析所用数据的统一入口。",
    ready: "已有数据",
    missing: "缺少数据",
    updated: "最新记录",
    status: "数据状态",
    manual: "手动添加",
    settings: "设置",
    restaurant: "餐厅",
    branches: "门店",
    team: "团队",
    integrations: "集成",
    language: "语言",
    account: "账户",
    insight: "下一步建议",
    noAlert: "目前没有已记录的提醒，但不代表所有数据都已完整。",
    viewMenu: "查看菜品",
    manage: "管理",
    retry: "重试",
    error: "无法加载数据，请重试。",
    loading: "加载中…",
    profitNote: "成本数据不完整时不显示利润。今日数据尚未完整，以餐厅时区为准。",
    history: "历史对话",
    tools: "更多选项",
    trend: "过去7个完整日的销售额",
    noTrend: "上传销售数据以查看趋势。",
    readOnly: "当前账户为只读，导入和连接由所有者管理。",
    saved: "数据已保存",
    analyze: "查看 AI 分析",
    manualNote: "请输入餐厅币种的今日金额，总成本包含损耗。手动汇总与导入交易单独保存，不重复累加。",
    waste: "损耗（已计入成本）",
    save: "保存并分析",
    totalCosts: "总成本",
    manualSource: "手动日汇总",
    manualConflict: "今日汇总已存在或数据已变化，请刷新后检查。",
    manualDisabled: "请选择门店后手动输入。",
    manualExisting: "今日已有手动汇总，不能重复添加。",
    manualUnavailable: "今日已有导入销售，请使用原始记录以免重复计算。"
  }
};
