export const copilotCopy = {
  ar: {
    unknown: "ما عندنا بيانات كافية لهذا الاستنتاج. أكمل استيراد البيانات للفترة المحددة.",
    revenue: "الإيراد المسجل",
    profit: "الربح التشغيلي المسجل",
    margin: "هامش الربح التشغيلي",
    orders: "عدد الطلبات المسجلة",
    aov: "متوسط قيمة الطلب",
    change: "تغيّر الإيراد",
    profitChange: "تغيّر الربح التشغيلي",
    foodChange: "تغيّر تكلفة الطعام",
    costChange: "تغيّر إجمالي التكاليف",
    top: "أعلى صنف بإيراد مسجل",
    worst: "أقل صنف بمساهمة مسجلة",
    best: "أعلى فرع بربح تشغيلي بين الفروع المكتملة",
    loss: "أكبر خسارة تشغيلية بين الفروع المكتملة",
    reprice: "أصناف تستحق مراجعة السعر",
    forecast: "توقع الإيراد للفترة القادمة",
    alerts: "التنبيهات المدعومة بالأدلة",
    review: "راجع هذا البند مع الفريق وتأكد من اكتمال البيانات قبل اتخاذ قرار.",
    cause:
      "الفرق المحاسبي يوضح البنود اللي تغيّرت، لكنه ما يثبت السبب التشغيلي. ما نقدر نجزم بهدر أو تغيّر طلب بدون دليل إضافي.",
    refused: "أقدر أحلل بياناتك المصرّح بها، لكن ما أنفّذ حذف أو تعديل تلقائي ولا أكشف بيانات خارج صلاحياتك.",
    clarify:
      "وش تبي تعرف بالتحديد؟ اسأل عن الإيراد، تغيّر الربح، تكلفة الطعام، تسعير الأصناف، الفروع، التنبيهات أو التوقعات، وحدد الفترة.",
    stale: "البيانات تغيرت بعد هذه الإجابة؛ أعد السؤال للحصول على تحليل محدث.",
    noCandidates: "ما ظهرت توصية تسعير مدعومة بالأدلة في البيانات المتاحة.",
    noLoss: "ما ظهرت خسارة تشغيلية في الفروع ذات البيانات المكتملة.",
    noAlerts: "ما ظهر تنبيه مؤكد؛ راجع حالات نقص البيانات قبل اعتبار الأداء طبيعيًا.",
    coverage:
      "المقارنة تخص السجلات المتاحة فقط؛ غياب السجل ما يعني صفر مبيعات. الأرباح لا تشمل الضرائب والفوائد والاستهلاك.",
    sources: "المصادر",
    period: "الفترة",
    summary: "ملخص الأداء",
    food: "تكلفة الطعام",
    recommendation: "توصية للمراجعة",
    insufficient: "غير متاح"
  },
  en: {
    unknown: "Insufficient evidence for this conclusion. Complete the imports for the selected period.",
    revenue: "Recorded revenue",
    profit: "Recorded operating profit",
    margin: "Operating profit margin",
    orders: "Recorded orders",
    aov: "Average order value",
    change: "Revenue change",
    profitChange: "Operating profit change",
    foodChange: "Food cost change",
    costChange: "Total cost change",
    top: "Highest recorded item revenue",
    worst: "Lowest recorded item contribution",
    best: "Highest operating profit among complete branches",
    loss: "Largest operating loss among complete branches",
    reprice: "Items for pricing review",
    forecast: "Revenue forecast for the upcoming period",
    alerts: "Evidence-backed alerts",
    review: "Review this item with the team and verify data completeness before acting.",
    cause:
      "The accounting difference identifies changed components, not the operational cause. Waste or demand changes require additional evidence.",
    refused:
      "I can analyze authorized data, but cannot automatically delete or change records or disclose data outside your access.",
    clarify:
      "Ask about revenue, profit changes, food costs, item pricing, branches, alerts or forecasts, and specify a period.",
    stale: "Data changed after this answer. Ask again for an updated analysis.",
    noCandidates: "No supported pricing candidate was found in the available evidence.",
    noLoss: "No operating loss was recorded among branches with complete evidence.",
    noAlerts: "No confirmed alert; inspect insufficient-data evaluations before concluding performance is healthy.",
    coverage:
      "Comparisons describe recorded evidence only. Missing records are not zero sales. Operating profit excludes tax, interest and depreciation.",
    sources: "Sources",
    period: "Period",
    summary: "Performance summary",
    food: "Food cost",
    recommendation: "Proposal for review",
    insufficient: "Unavailable"
  },
  zh: {
    unknown: "该结论的证据不足，请补充所选期间的导入数据。",
    revenue: "记录收入",
    profit: "记录营业利润",
    margin: "营业利润率",
    orders: "记录订单数",
    aov: "平均订单金额",
    change: "收入变化",
    profitChange: "营业利润变化",
    foodChange: "食材成本变化",
    costChange: "总成本变化",
    top: "记录收入最高的商品",
    worst: "记录贡献利润最低的商品",
    best: "完整数据门店中营业利润最高者",
    loss: "完整数据门店中营业亏损最大者",
    reprice: "建议审核价格的商品",
    forecast: "未来期间收入预测",
    alerts: "有证据支持的提醒",
    review: "请与团队审核该项目，并在决策前核实数据完整性。",
    cause: "会计差异说明哪些项目发生变化，不证明运营原因。浪费或需求变化需要额外证据。",
    refused: "我可以分析获授权数据，但不会自动删除或修改记录，也不会披露权限外的数据。",
    clarify: "请询问收入、利润变化、食材成本、商品定价、门店、提醒或预测，并指定期间。",
    stale: "此回答之后数据已更新，请重新提问。",
    noCandidates: "现有证据中没有需调整价格的候选商品。",
    noLoss: "数据完整的门店未记录营业亏损。",
    noAlerts: "没有确认的提醒；请先检查证据不足的项目。",
    coverage: "比较仅描述已记录的证据。缺失记录并非零销售。营业利润不包含税费、利息和折旧。",
    sources: "来源",
    period: "期间",
    summary: "经营摘要",
    food: "食材成本",
    recommendation: "待审核建议",
    insufficient: "不可用"
  }
};
